- name: Checkmarx AST Github Action
  # You may pin to the exact commit or the version.
  # uses: Checkmarx/ast-github-action@72d549beebd0bc5bbafa559f198161b6ce7c03df
  uses: Checkmarx/ast-github-action@2.0.21
  with:
    # Provide the AST portal URL
    base_uri: https://eu.ast.checkmarx.net/
    # Provide the Tenant for AST portal URL
    cx_tenant: beta_nova8
    # Client ID for AST portal authentication
    cx_client_id: ${{ secrets.sec_cmo_id }}
    # Secret key for AST portal authentication
    cx_client_secret: ${{ secrets.sec_cmo_secret }}
    # Select a Checkmarx Project Name
    project_name: WebGoat
    # Branch name
    branch: main
    # GitHub API Token
    github_token: # optional, default is ${{ github.token }}
    # Additional parameters for AST scan
    additional_params: # optional, default is 
    # Repository name for PR decoration
    repo_name: # optional, default is ${{ github.event.repository.name }}
    # Organization name to create the Pr comment
    namespace: # optional, default is ${{ github.repository_owner }}
    # Pr Number of the pull request that needs the decoration
    pr_number: # optional, default is ${{ github.event.number }}
